### ISSUE TITLE
Workspace creation with admin fails 

### ISSUE THREAD

**Issue by VojtaStanek** [contember/engine#169]
```
$ npx contember workspace:create test-workspace --with-admin
Error: dest already exists.
    at /home/vojta/.nvm/versions/node/v14.11.0/lib/node_modules/@contember/cli/node_modules/fs-extra/lib/move/move.js:41:31
    at /home/vojta/.nvm/versions/node/v14.11.0/lib/node_modules/@contember/cli/node_modules/universalify/index.js:22:54
```

(I am logged in to verdaccio)

**Comment by VojtaStanek** [comment]
This command was removed and replaced.
