### ISSUE TITLE
column person.disabled_at does not exist

### ISSUE THREAD

**Issue by iBobik** [contember/engine#466]
Just upgraded from 1.3.0-alpha.13 to 1.3.0-rc.1, but user login failing.

```
2023-07-23 17:48:00 2023-07-23T15:47:59.976Z debug Request processing started
2023-07-23 17:48:00                                POST /tenant #38684199030253597
2023-07-23 17:48:00                                module: 'tenant'
2023-07-23 17:48:00                                body: {
2023-07-23 17:48:00                                  query: '\n' +
2023-07-23 17:48:00                                    '    mutation UserLogin($email: String!, $password: String!) {\n' +
2023-07-23 17:48:00                                    '  result: signIn(email: $email, password: $password, expiration: 604800) {\n' +
2023-07-23 17:48:00                                    '    ok\n' +
2023-07-23 17:48:00                                    '    result {\n' +
2023-07-23 17:48:00                                    '      token\n' +
2023-07-23 17:48:00                                    '    }\n' +
2023-07-23 17:48:00                                    '    error {\n' +
2023-07-23 17:48:00                                    '      code\n' +
2023-07-23 17:48:00                                    '      developerMessage\n' +
2023-07-23 17:48:00                                    '    }\n' +
2023-07-23 17:48:00                                    '  }\n' +
2023-07-23 17:48:00                                    '}\n' +
2023-07-23 17:48:00                                    '    ',
2023-07-23 17:48:00                                  variables: { email: 'xxx', password: 'xxx' },
2023-07-23 17:48:00                                  operationName: 'UserLogin'
2023-07-23 17:48:00                                }
2023-07-23 17:48:00                                query: [Object: null prototype] {}
2023-07-23 17:48:00 2023-07-23T15:48:00.021Z debug User authenticated
2023-07-23 17:48:00                                POST /tenant #38684199030253597
2023-07-23 17:48:00                                module: 'tenant'
2023-07-23 17:48:00                                authResult: {
2023-07-23 17:48:00                                  identityId: 'e2830b51-712f-4837-9446-b3df877f25e0',
2023-07-23 17:48:00                                  apiKeyId: '414f8598-ab6b-4cf8-9b1b-28d96735ca8b',
2023-07-23 17:48:00                                  roles: [ 'login' ],
2023-07-23 17:48:00                                  personId: null,
2023-07-23 17:48:00                                  valid: true,
2023-07-23 17:48:00                                  assumedIdentityId: undefined
2023-07-23 17:48:00                                }
2023-07-23 17:48:00 2023-07-23T15:48:00.021Z debug Tenant query processing started
2023-07-23 17:48:00                                POST /tenant #38684199030253597
2023-07-23 17:48:00                                module: 'tenant'
2023-07-23 17:48:00                                user: 'e2830b51-712f-4837-9446-b3df877f25e0'
2023-07-23 17:48:00 2023-07-23T15:48:00.030Z error Database query error: column person.disabled_at does not exist
2023-07-23 17:48:00                                SQL: select "person"."id", "person"."password_hash", "person"."otp_uri", "person"."otp_activated_at", "person"."identity_id", "person"."email", "person"."name", "person"."disabled_at", "identity"."roles"  from "tenant"."person" inner join  "tenant"."identity" as "identity" on  "identity"."id" = "person"."identity_id"  where "person"."email" = ?
2023-07-23 17:48:00                                parameters: honza+content-admin@poboril.cz
2023-07-23 17:48:00                                POST /tenant #38684199030253597
2023-07-23 17:48:00                                module: 'tenant'
2023-07-23 17:48:00                                user: 'e2830b51-712f-4837-9446-b3df877f25e0'
2023-07-23 17:48:00                                QueryError: Database query error: column person.disabled_at does not exist
2023-07-23 17:48:00                                SQL: select "person"."id", "person"."password_hash", "person"."otp_uri", "person"."otp_activated_at", "person"."identity_id", "person"."email", "person"."name", "person"."disabled_at", "identity"."roles"  from "tenant"."person" inner join  "tenant"."identity" as "identity" on  "identity"."id" = "person"."identity_id"  where "person"."email" = ?
2023-07-23 17:48:00                                parameters: honza+content-admin@poboril.cz
2023-07-23 17:48:00                                    at /src/server.js:12460:23
2023-07-23 17:48:00                                    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-23 17:48:00                                    at async Mutex.execute (/src/server.js:5805:18)
2023-07-23 17:48:00                                    at async AcquiredConnection.query (/src/server.js:12423:16)
2023-07-23 17:48:00                                    at async Connection.scope (/src/server.js:12503:26)
2023-07-23 17:48:00                                    at async SelectBuilder.getResult (/src/server.js:10985:24)
2023-07-23 17:48:00                                    at async PersonQuery.fetch (/src/server.js:108587:18)
2023-07-23 17:48:00                                    at async QueryHandler.fetch (/src/server.js:11699:16)
2023-07-23 17:48:00                                    at async PersonByEmailFallbackQuery.fetch (/src/server.js:108598:19)
2023-07-23 17:48:00                                    at async QueryHandler.fetch (/src/server.js:11699:16) {
2023-07-23 17:48:00                                  previous: error: column person.disabled_at does not exist
2023-07-23 17:48:00                                      at Parser.parseErrorMessage (/src/server.js:8818:99)
2023-07-23 17:48:00                                      at Parser.handlePacket (/src/server.js:8659:25)
2023-07-23 17:48:00                                      at Parser.parse (/src/server.js:8583:35)
2023-07-23 17:48:00                                      at Socket.<anonymous> (/src/server.js:8859:45)
2023-07-23 17:48:00                                      at Socket.emit (node:events:514:28)
2023-07-23 17:48:00                                      at Socket.emit (node:domain:489:12)
2023-07-23 17:48:00                                      at addChunk (node:internal/streams/readable:324:12)
2023-07-23 17:48:00                                      at readableAddChunk (node:internal/streams/readable:297:9)
2023-07-23 17:48:00                                      at Readable.push (node:internal/streams/readable:234:10)
2023-07-23 17:48:00                                      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
2023-07-23 17:48:00                                    length: 117,
2023-07-23 17:48:00                                    severity: 'ERROR',
2023-07-23 17:48:00                                    code: '42703',
2023-07-23 17:48:00                                    detail: undefined,
2023-07-23 17:48:00                                    hint: undefined,
2023-07-23 17:48:00                                    position: '157',
2023-07-23 17:48:00                                    internalPosition: undefined,
2023-07-23 17:48:00                                    internalQuery: undefined,
2023-07-23 17:48:00                                    where: undefined,
2023-07-23 17:48:00                                    schema: undefined,
2023-07-23 17:48:00                                    table: undefined,
2023-07-23 17:48:00                                    column: undefined,
2023-07-23 17:48:00                                    dataType: undefined,
2023-07-23 17:48:00                                    constraint: undefined,
2023-07-23 17:48:00                                    file: 'parse_relation.c',
2023-07-23 17:48:00                                    line: '3638',
2023-07-23 17:48:00                                    routine: 'errorMissingColumn'
2023-07-23 17:48:00                                  },
2023-07-23 17:48:00                                  code: '42703',
2023-07-23 17:48:00                                  originalMessage: 'column person.disabled_at does not exist',
2023-07-23 17:48:00                                  sql: 'select "person"."id", "person"."password_hash", "person"."otp_uri", "person"."otp_activated_at", "person"."identity_id", "person"."email", "person"."name", "person"."disabled_at", "identity"."roles"  from "tenant"."person" inner join  "tenant"."identity" as "identity" on  "identity"."id" = "person"."identity_id"  where "person"."email" = ?',
2023-07-23 17:48:00                                  parameters: [ 'xxx' ],
2023-07-23 17:48:00                                  constraint: undefined,
2023-07-23 17:48:00                                  table: undefined
2023-07-23 17:48:00                                }
```

It did not helped to recreate engine container. I had to remove also database, import production data, then it works.

**Comment by matej21** [comment]
Hello,
Thank you for reporting this. We are already aware of this issue - it is an issue with migrations affecting engine upgrades in some scenarios.
Here is a PR #459 that should prevent such problems in the future.
